### ISSUE TITLE
Help implementing differential drive

### ISSUE THREAD

**Issue by ricardojlrufino** [le-james/differential-drive-robot#1]
Hi, I'm trying to implement a 2 wheel robot simulator but I'm stuck on the math part.

I read some of the theory, but as it's been a while since I left college, I'm not acknowledging the terms.

Basically I have 2 speed controls for the robot wheels. If I move L_VEL to max. and leave the R_VEL at 0. I believe the rotation he is doing is not correct...

The Code can be edited online:
https://playground.babylonjs.com/#5LD51R#33

can you help?

**Comment by le-james** [comment]
Hey,

I found this useful for understanding the differential drive motion: **https://www.cs.columbia.edu/~allen/F17/NOTES/icckinematics.pdf**

Section 1 Differential Drive Kinematics of the PDF is useful. The robot should satisfy the three conditions at the beginning of page 2.

Hopefully that helps!

**Comment by ricardojlrufino** [comment]
Hi!
Funny, I've already seen the article, but as I'm out of math practice, I have no idea where the "error" is.

I'll try again later with a clearer head!
If you can take a look and see if you think how to improve:
https://playground.babylonjs.com/#5LD51R#33

I thank you for your attention.

**Comment by le-james** [comment]
Yeah, there is something wrong with the rotation of the robot in the code.

Maybe this will clear up the issue?...
![image](https://user-images.githubusercontent.com/57570353/160306123-b536e16b-ce66-4ded-af22-82e35ef50c49.png)
From the image above, the point **ICC is where the robot should rotate around** and is governed by: 
![image](https://user-images.githubusercontent.com/57570353/160306212-02359c90-65eb-40cf-805c-4d71913f98d6.png)
R is the distance from the center of the wheel axis to the ICC point and l is the distance between the two wheels and Vl and Vr are the left and right wheel velocities. So R should change as the sliders are changed in your code. ICC is an imaginary point along the axis of the wheel base. The rate of rotation around the ICC point is governed by: 
![image](https://user-images.githubusercontent.com/57570353/160306559-bd933ccc-34cd-4f43-8257-b5f2e93a17f5.png)
I think you may also need a negative range for the sliders if you use these equations. Also for backwards motion of the robot.

Would also need to also satisfy these three conditions:
For 1, R would have a division by 0 so a check may also be needed.
![image](https://user-images.githubusercontent.com/57570353/160306858-4099e5aa-aa51-4931-9396-cb8ff1fec7a4.png)

Let me know if that helps.
